### ISSUE TITLE
Compare against an array of image URL's

### ISSUE THREAD

**Issue by ingeniousgenius** [NTech-Lab/ffserver-examples#1]
How could I use the PHP of Java script to compare against an array of image url's from my server? The array will be quite large, thousands of urls/

**Comment by Priority1** [comment]
Hey Jesse!

First of all, if you want to compare faces from those images, you need to enroll all the images to the server. The only way to do that is to PUT those images to the server in a loop one by one. If we talk about standalone installation - you can use up to N threads, where N is count of your physical CPU cores.

**Comment by ingeniousgenius** [comment]
Hey,

I'm sorry I'm not that good at this type of development. I'm more of a mobile (iOS) developer than anything else. How could I enroll the images in the server and loop them one by one? What do you mean by that?

**Comment by alexanderk23** [comment]
@jesster2k10 Hi Jesse, 
[Here is a sample PHP code](https://gist.github.com/alexanderk23/8cde2992d53951c51cc67651c5e2a4ab) to enroll an array of photo URIs to the server. Basically it's an example code from this repo but with `enroll` method added and some typos fixed. You may find it useful for your task.

**Comment by ingeniousgenius** [comment]
@alexanderk23 

Thanks for the script, I'm actually quite the PHP noob. If I wanted to run this script, would I just do this

       include('example.php');
       $api = new FacenAPI();
       $api->enroll($photo_url, $optvars = NULL);

Also, I want to pull the URL's (image url's) from a MySql Colum into an array but I fear as I might have up to 1 Billion rows in the future, it may take way too much storage or too long. Do you have any suggestions on how to do that? If not I totally understand, you're not obliged to tell me in the first place. 

Thanks

**Comment by alexanderk23** [comment]
@jesster2k10 yeah, something like that (look at lines 167-178 of the gist). But, instead of trying to fetch whole set of URIs from MySQL into an array I'd rather fetch and enroll them one-by-one in a cycle using [mysqli_fetch_row](http://php.net/manual/en/mysqli-result.fetch-row.php). Also you can speed up things a bit by splitting the dataset into chunks (ex. by primary key value) and running a script instance for each chunk in parallel.

**Comment by ingeniousgenius** [comment]
https://107.180.50.176/~yogesh87/faces/service.php that's the database. I'll take into account what you said.
